name: Build and Deploy Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Docker image tag
        required: true

env:
  DOCKER_HUB_USERNAME: lb1001
  DOCKER_HUB_PASSWORD: dckr_pat_7_WiztugPk9bPRnT8hCuBrPxM5U
  DOCKER_IMAGE_NAME: lb1001/tech_portal
  DOCKER_IMAGE_TAG: ${{ github.event.inputs.tag }}
  DOCKER_CONTAINER_NAME: tech_portal
  REMOTE_HOST: www.lb1001.tech
  REMOTE_USERNAME: root
  REMOTE_PASSWORD: Luobiao1990

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
        file: build.dockerfile

    - name: Deploy Docker image to remote host
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ env.REMOTE_HOST }}
        username: ${{ env.REMOTE_USERNAME }}
        password: ${{ env.REMOTE_PASSWORD }}
        script: |
          docker login -u ${{ env.DOCKER_HUB_USERNAME }} -p ${{ env.DOCKER_HUB_PASSWORD }}
          if [[ -z "$(docker images -q ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} 2> /dev/null)" ]]; then
            docker pull ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
          fi
          echo pull ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} success...
          if [[ -n "$(docker ps -a | grep ${{ env.DOCKER_CONTAINER_NAME }})" ]]; then
            docker stop ${{ env.DOCKER_CONTAINER_NAME }} || true
            docker rm ${{ env.DOCKER_CONTAINER_NAME }} || true
          fi
          docker run -d --name ${{ env.DOCKER_CONTAINER_NAME }} -p 80:80 -p 443:443 ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
