name: Docker Image Auto Deployment

on:
#   push:
#     branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tag:
        description: docker image tag
        required: true
env:
  dockerTag: ${{github.event.inputs.tag}}
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: lb1001
        password: dckr_pat_7_WiztugPk9bPRnT8hCuBrPxM5U
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: lb1001/tech_portal:${{env.dockerTag}}
        file: build.dockerfile
        
    - name: SSH into Remote Host
      uses: appleboy/ssh-action@master
      with:
          host: www.lb1001.tech
          username: root
          password: Luobiao1990
    - name: Pull Docker Image
      run: docker pull lb1001/tech_portal:${{env.dockerTag}}
      
    - name: Start Docker Container
      run: docker run -d --name lb1001.tech.portal -p 80:80 lb1001/tech_portal:${{env.dockerTag}}
    
      
